<?php

/**
 * Created by PhpStorm.
 * User: datdao
 * Date: 6/13/17
 * Time: 5:52 AM
 */
class CalculatorTest2 extends PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    //a
}